# Generated by Django 5.2.3 on 2026-02-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0003_servicecategory_remove_serviceprovider_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True),
        ),
    ]
