# Generated by Django 5.2.3 on 2026-03-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0007_servicerequest_latitude_servicerequest_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_price',
        ),
    ]
