# Generated by Django 5.2.3 on 2026-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0008_remove_service_max_price_remove_service_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
