# Generated by Django 5.2.3 on 2026-06-28 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0009_service_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='Match.serviceprovider'),
        ),
    ]
