# Generated by Django 5.2.3 on 2026-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0013_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_notes',
            field=models.TextField(blank=True, help_text="Write what's missing or invalid here (e.g. 'KRA PIN certificate is blurry, please re-upload'). This text is emailed to the provider whenever you save a change to it."),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('needs_changes', 'Needs Changes'), ('rejected', 'Rejected')], default='pending', help_text="Overall status of this provider's credential review.", max_length=20),
        ),
    ]
