# Generated by Django 5.2.3 on 2026-07-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0014_serviceprovider_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Your starting price for this service, in KES (e.g. 1500). Shown to customers as 'From KES X'. Leave blank if you haven't set a rate yet — you'll be reminded on your dashboard.", max_digits=10, null=True),
        ),
    ]
